version: '3'

services:
    flask:
        build:
            context: .
            dockerfile: docker/Dockerfile-flask
        volumes:
            - "./api:/app"
        environment:
            - PYTHONUNBUFFERED=0
            - PYTHONPYCACHEPREFIX=../__pycache__
            - FLASK_APP=app.py
        ports:
            - "5002:5002"
        entrypoint: /app/entrypoint.sh

    node:
        build:
            context: .
            dockerfile: docker/Dockerfile-node
        ports:
            - "3000:3000"
        volumes:
            - "./image_app:/app"
