version: '3'

services:
    flask:
        build:
            context: .
            dockerfile: docker/Dockerfile-flask
        volumes:
            - "./api:/app"
        environment:
            - PYTHONUNBUFFERED=0
            - PYTHONPYCACHEPREFIX=../__pycache__
            - FLASK_APP=app.py
        ports:
            - "5002:5002"
        command: python -m flask run --host=0.0.0.0 --port=5002

    node:
        build:
            context: .
            dockerfile: docker/Dockerfile-node
        ports:
            - "3000:3000"
        volumes:
            - "./image_app:/app"
