# Based on Node 10.x LTS image
FROM node:16.10.0-alpine

# Set the default directory where CMD will execute
WORKDIR /app
COPY image_app .
# Set the default command to execute when creating a new container
CMD ["/bin/bash", "-c", " yarn && yarn start"]

# Install system requirements
RUN apk add --no-cache build-base bash asciidoctor