FROM python:3.10.8-alpine
WORKDIR /app

RUN apk --update --upgrade add --no-cache  gcc musl-dev jpeg-dev zlib-dev libffi-dev cairo-dev pango-dev gdk-pixbuf-dev

RUN python -m pip install --upgrade pip
COPY api/requirements.txt requirements.txt
COPY api/entrypoint.sh entrypoint.sh
RUN pip install -r requirements.txt
EXPOSE 5002
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]