"""empty message

Revision ID: 357c18b2e24b
Revises: 
Create Date: 2022-12-16 07:42:30.012402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "357c18b2e24b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_upload",
        sa.Column("image_id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("image_name", sa.String(length=255), nullable=False),
        sa.Column("image_location", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("image_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("image_upload")
    # ### end Alembic commands ###
